import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJs Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        css={css`
          margin: 0 auto;
          width: fit-content;
          background-color: green;
        `}
      >
        NextJs Starter
      </div>
    </div>
  );
};

export default Home;
