import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { FormItem, Input } from "@components/ui";
import { css } from "@emotion/react";
import { useForm } from "react-hook-form";

const Banner = styled.div`
  width: 100%;
  height: 300px;
  background: no-repeat url("/images/banner-test.jpg");
  background-size: 100% 100%;
`;

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  const onSubmit = (data: any) => console.log(data);
  return (
    <div
      css={css`
        padding-top: 80px;
        width: 320px;
        margin: 0 auto;
      `}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content="https://picsum.photos/id/237/200/300"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(onSubmit)}>
        <FormItem
          label="아이디"
          css={css`
            width: 300px;
          `}
        >
          <Input defaultValue="test" formName="test" register={register} />
        </FormItem>
        <FormItem
          label="패스워드"
          css={css`
            width: 300px;
          `}
        >
          <Input formName="password" register={register} />
          {errors.exampleRequired && <span>This field is required</span>}
        </FormItem>
        <input type="submit" />
      </form>
    </div>
  );
};

export default Home;
