import type { NextPage } from "next";
import Head from "next/head";
import { Typography } from "@components/ui";
import { css } from "@emotion/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content="https://picsum.photos/id/237/200/300"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography.Text
        css={css`
          font-size: 32px;
        `}
      >
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js StarterHello Next-js StarterHello Next-js
        StarterHello Next-js Starterv
      </Typography.Text>
    </div>
  );
};

export default Home;
